// Automatically generated by MockGen. DO NOT EDIT!
// Source: pkg/interfaces/interfaces.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Kube2Consul interface
type MockKube2Consul struct {
	ctrl     *gomock.Controller
	recorder *_MockKube2ConsulRecorder
}

// Recorder for MockKube2Consul (not exported)
type _MockKube2ConsulRecorder struct {
	mock *MockKube2Consul
}

func NewMockKube2Consul(ctrl *gomock.Controller) *MockKube2Consul {
	mock := &MockKube2Consul{ctrl: ctrl}
	mock.recorder = &_MockKube2ConsulRecorder{mock}
	return mock
}

func (_m *MockKube2Consul) EXPECT() *_MockKube2ConsulRecorder {
	return _m.recorder
}

func (_m *MockKube2Consul) NodeIPByPodIP(_param0 string) string {
	ret := _m.ctrl.Call(_m, "NodeIPByPodIP", _param0)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockKube2ConsulRecorder) NodeIPByPodIP(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NodeIPByPodIP", arg0)
}
